dofile(minetest.get_modpath("buildtest").."/pipes/wood.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/cobble.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/stone.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/iron.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/gold.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/diamond.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/obsidian.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/sandstone.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/emriald.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/gate.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/stripe.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/mesecon.lua")

dofile(minetest.get_modpath("buildtest").."/pipes/diamese.lua")
dofile(minetest.get_modpath("buildtest").."/pipes/mese.lua")